permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: 马超
  email: drizzt@aliyun.com
  link: http://blog.drizzt.cn
  weibo: http://weibo.com/drizztblog
  github: http://github.com/DrizztM

# 站点信息
title: 马超的博客 
description: 马超的博客
url: http://blog.drizzt.cn
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar:  /assets/img/logo.png
favicon:  /assets/img/logo.png

# google analytics 设置
ga:
  id: UA-54767140-1
  url: yansu.org

# disqus 设置
disqus:
  shortname: drizztblog