permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: 马超
  email: drizzt@aliyun.com
  weibo: http://weibo.com/drizztblog
  github: http://github.com/drizztm

# 站点信息
title: 马超和魏利洁
description: 
url: http://blog.drizzt.cn
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/logo.png
favicon: /public/img/logo.png

# disqus 设置
disqus:
  shortname: drizztm

# 主题设置，自动激活某个标签
active: 相册

# 首页除了最新文章外显示分类
cates: 
  - 生日

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档